CallCenterDashboard1/Controllers/CallCenterController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Core.EntityClient;
using System.Data.SqlClient;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CallCenterDashboard1.EDMX;
using Newtonsoft.Json.Linq;

namespace CallCenterDashboard1.Controllers
{
    [Authorize]
    public class CallCenterController : Controller
    {
        // GET: CallCenter
        public ActionResult Dashboard()
        {
            return View("Dashboard");
        }


        public ActionResult UserInfo()
        {
            ViewBag.Message = "Your UserInfo page.";

            return View();
        }

        public ActionResult OperationProgress()
        {
            ViewBag.Message = "";

            return View();
        }

        public ActionResult OperationScript()
        {
            ViewBag.Message = "";

            return View();
        }

        public ActionResult Clock()
        {
            ViewBag.Message = "";

            return View();
        }

        public ActionResult Separator()
        {
            ViewBag.Message = "";

            return View();
        }

        public async Task<ActionResult> IndividualsList(string operationKey = null)
        {
            operationKey = Convert.ToString(9);

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Globals.Configuration.DATA_INTERFACE_URL);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                StringBuilder requestUriBuilder = new StringBuilder();
                requestUriBuilder.Append("CallCenter/getCallStatuses/");
                requestUriBuilder.Append("?");
                requestUriBuilder.AppendFormat("operationKey={0}", operationKey);

                HttpResponseMessage response = await client.GetAsync(requestUriBuilder.ToString()).ConfigureAwait(false);
                response.EnsureSuccessStatusCode();
                if (response.IsSuccessStatusCode)
                {
                    string responseJSON = await response.Content.ReadAsStringAsync();

                    var result = JsonConvert.DeserializeObject<List<GetIndividualsByOperation_Result>>(responseJSON);

                    //List<string> resultStatic = new List<string>();
                    //resultStatic.Add("Call Pending");
                    //resultStatic.Add("Call Back");
                    //resultStatic.Add("Wrong Number");
                    //resultStatic.Add("No Answer");
                    //resultStatic.Add("Completed");

                    //ViewBag.CallStatusList = resultStatic.ToList();
                    ViewBag.CallStatusList = result.Select(x => x.Value).ToList().Distinct();
                }
            }

            return View();
        }


        public async Task<string> fillOperationsDropDown()
        {
            string result = string.Empty;
            List<string> Result = new List<string>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Globals.Configuration.DATA_INTERFACE_URL);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                StringBuilder requestUriBuilder = new StringBuilder();
                requestUriBuilder.Append("/CallCenter/getOperationsInfoByUser");
                requestUriBuilder.Append("?");
                requestUriBuilder.AppendFormat("userName={0}", User.Identity.Name);

               HttpResponseMessage response = await client.GetAsync(requestUriBuilder.ToString()).ConfigureAwait(false);
                response.EnsureSuccessStatusCode();
               if (response.IsSuccessStatusCode)
                {
                    string responseJSON = await response.Content.ReadAsStringAsync();

                   result = Convert.ToString(JsonConvert.DeserializeObject(responseJSON));

                    //string responseJSONInner = "[" + await response.Content.ReadAsStringAsync() + "]";
                    //var Answerscount = JArray.Parse(responseJSONInner).Children();

                    //Answerscount

                    //ViewBag.CallStatusList = resultStatic.ToList();
                    //ViewBag.OperationList = result.Select(x => x.Value).ToList().Distinct();
               }
            }
             
            return result;
        }

        public async Task<string> displayOperationInformation(int operationKey)
        {
            string result = string.Empty;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Globals.Configuration.DATA_INTERFACE_URL);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                StringBuilder requestUriBuilder = new StringBuilder();
                requestUriBuilder.Append("/CallCenter/getOperationsInfoByUser");
                requestUriBuilder.Append("?");
                requestUriBuilder.AppendFormat("operationKey={0}", operationKey);
                requestUriBuilder.Append("&");
                requestUriBuilder.AppendFormat("userName={0}", User.Identity.Name);

                HttpResponseMessage response = await client.GetAsync(requestUriBuilder.ToString()).ConfigureAwait(false);
                response.EnsureSuccessStatusCode();
                if (response.IsSuccessStatusCode)
                {
                    string responseJSON = await response.Content.ReadAsStringAsync();

                    result = Convert.ToString(JsonConvert.DeserializeObject(responseJSON));

                    //ViewBag.CallStatusList = resultStatic.ToList();
                    //ViewBag.OperationList = result.Select(x => x.Value).ToList().Distinct();
                }
            }

            return result;
        }

        public async Task<JsonResult> fillOverallProgressBar()
        {
            string result = string.Empty;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Globals.Configuration.DATA_INTERFACE_URL);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                StringBuilder requestUriBuilder = new StringBuilder();
                requestUriBuilder.Append("/CallCenter/getOverallProgress");
                //requestUriBuilder.Append("?");
                //requestUriBuilder.AppendFormat("operationKey={0}", operationKey);

                HttpResponseMessage response = await client.GetAsync(requestUriBuilder.ToString()).ConfigureAwait(false);
                response.EnsureSuccessStatusCode();
                if (response.IsSuccessStatusCode)
                {
                    string responseJSON = await response.Content.ReadAsStringAsync();

                    result = Convert.ToString(JsonConvert.DeserializeObject(responseJSON));

                    //ViewBag.CallStatusList = resultStatic.ToList();
                    //ViewBag.OperationList = result.Select(x => x.Value).ToList().Distinct();
                }
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> fillOperationProgressBar(int operationKey)
        {
            string result = string.Empty;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Globals.Configuration.DATA_INTERFACE_URL);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                StringBuilder requestUriBuilder = new StringBuilder();
                requestUriBuilder.Append("/CallCenter/getOperationProgressByUser");
                requestUriBuilder.Append("?");
                requestUriBuilder.AppendFormat("operationKey={0}", operationKey);
                requestUriBuilder.Append("&");
                requestUriBuilder.AppendFormat("userName={0}", User.Identity.Name);

                HttpResponseMessage response = await client.GetAsync(requestUriBuilder.ToString()).ConfigureAwait(false);
                response.EnsureSuccessStatusCode();
                if (response.IsSuccessStatusCode)
                {
                    string responseJSON = await response.Content.ReadAsStringAsync();

                    result = Convert.ToString(JsonConvert.DeserializeObject(responseJSON));

                    //ViewBag.CallStatusList = resultStatic.ToList();
                    //ViewBag.OperationList = result.Select(x => x.Value).ToList().Distinct();
                }
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //getRemainingIndividuals
        public async Task<string> fillRemainingProgressBar(int operationKey) //NOT DONE
        {
            string result = string.Empty;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Globals.Configuration.DATA_INTERFACE_URL);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                StringBuilder requestUriBuilder = new StringBuilder();
                requestUriBuilder.Append("/CallCenter/getRemainingIndividualsByUser");
                requestUriBuilder.Append("?");

CallCenterDashboard1/Controllers/FAQsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CallCenterDashboard1.EDMX;

namespace CallCenterDashboard1.Controllers
{
    public class FAQsController : Controller
    {
        private PMCallCenterEntities db = new PMCallCenterEntities();

        // GET: FAQs
        public ActionResult Index()
        {
            var fAQs = db.FAQs.Include(f => f.AnswerTemplate).Include(f => f.Operation).Include(f => f.Question);
            return View(fAQs.ToList());
        }

        // GET: FAQs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FAQ fAQ = db.FAQs.Find(id);
            if (fAQ == null)
            {
                return HttpNotFound();
            }
            return View(fAQ);
        }

        // GET: FAQs/Create
        public ActionResult Create()
        {
            ViewBag.AnswerTemplateKey = new SelectList(db.AnswerTemplates, "AnswerTemplateKey", "Value");
            ViewBag.OperationKey = new SelectList(db.Operations, "OperationKey", "Name");
            ViewBag.QuestionKey = new SelectList(db.Questions, "QuestionKey", "Text");
            return View();
        }

        // POST: FAQs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FAQKey,QuestionKey,AnswerTemplateKey,FAQType,OperationKey")] FAQ fAQ)
        {
            if (ModelState.IsValid)
            {
                db.FAQs.Add(fAQ);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AnswerTemplateKey = new SelectList(db.AnswerTemplates, "AnswerTemplateKey", "Value", fAQ.AnswerTemplateKey);
            ViewBag.OperationKey = new SelectList(db.Operations, "OperationKey", "Name", fAQ.OperationKey);
            ViewBag.QuestionKey = new SelectList(db.Questions, "QuestionKey", "Text", fAQ.QuestionKey);
            return View(fAQ);
        }

        // GET: FAQs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FAQ fAQ = db.FAQs.Find(id);
            if (fAQ == null)
            {
                return HttpNotFound();
            }
            ViewBag.AnswerTemplateKey = new SelectList(db.AnswerTemplates, "AnswerTemplateKey", "Value", fAQ.AnswerTemplateKey);
            ViewBag.OperationKey = new SelectList(db.Operations, "OperationKey", "Name", fAQ.OperationKey);
            ViewBag.QuestionKey = new SelectList(db.Questions, "QuestionKey", "Text", fAQ.QuestionKey);
            return View(fAQ);
        }

        // POST: FAQs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FAQKey,QuestionKey,AnswerTemplateKey,FAQType,OperationKey")] FAQ fAQ)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fAQ).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AnswerTemplateKey = new SelectList(db.AnswerTemplates, "AnswerTemplateKey", "Value", fAQ.AnswerTemplateKey);
            ViewBag.OperationKey = new SelectList(db.Operations, "OperationKey", "Name", fAQ.OperationKey);
            ViewBag.QuestionKey = new SelectList(db.Questions, "QuestionKey", "Text", fAQ.QuestionKey);
            return View(fAQ);
        }

        // GET: FAQs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FAQ fAQ = db.FAQs.Find(id);
            if (fAQ == null)
            {
                return HttpNotFound();
            }
            return View(fAQ);
        }

        // POST: FAQs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FAQ fAQ = db.FAQs.Find(id);
            db.FAQs.Remove(fAQ);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CallCenterDashboard1/Views/CallCenter/Clock.cshtml
@{
    Layout = null;
}
<head>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/font-awesome.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/simple-line-icons.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/bootstrap-switch.min.css")" rel="stylesheet" type="text/css" />
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="@Url.Content("~/Content/morris.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/mapplic.css")" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN THEME GLOBAL STYLES -->
<link href="@Url.Content("~/Content/components.min.css")" rel="stylesheet" id="style_components" type="text/css" />
<link href="@Url.Content("~/Content/plugins.min.css")" rel="stylesheet" type="text/css" />
<!-- END THEME GLOBAL STYLES -->
<!-- BEGIN THEME LAYOUT STYLES -->
<link href="@Url.Content("~/Content/layout.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/custom.min.css")" rel="stylesheet" type="text/css" />
<!-- END THEME LAYOUT STYLES -->
<link href="@Url.Content("~/Content/select2.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/select2.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/select2-bootstrap.min.css")" rel="stylesheet" type="text/css" />

<link href="@Url.Content("~/Content/components-md.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/CustomOverlay.css")" rel="stylesheet" type="text/css" />

<link rel="shortcut icon" href="favicon.ico" />
</head>
<body onLoad="myclock('analog-clock'); show();">
    <canvas id="analog-clock" style="width: 250px; position: absolute; top: 50%; left:50%; transform: translate(-50%,-50%)"></canvas>
</body>
<script src="@Url.Content("~/Scripts/Clock.js")" type="text/javascript"></script>


<script src="@Url.Content("~/Scripts/jquery.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/js.cookie.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.slimscroll.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.blockui.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/bootstrap-switch.min.js")" type="text/javascript"></script>

CallCenterDashboard1/Views/CallCenter/FAQs.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/font-awesome.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/simple-line-icons.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-switch.min.css")" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="@Url.Content("~/Content/morris.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/mapplic.css")" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN THEME GLOBAL STYLES -->
    <link href="@Url.Content("~/Content/components.min.css")" rel="stylesheet" id="style_components" type="text/css" />
    <link href="@Url.Content("~/Content/plugins.min.css")" rel="stylesheet" type="text/css" />
    <!-- END THEME GLOBAL STYLES -->
    <!-- BEGIN THEME LAYOUT STYLES -->
    <link href="@Url.Content("~/Content/layout.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/custom.min.css")" rel="stylesheet" type="text/css" />
    <!-- END THEME LAYOUT STYLES -->
    <link href="@Url.Content("~/Content/select2.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/select2.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/select2-bootstrap.min.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/Content/components-md.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/CustomOverlay.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/_all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/grey.css")" rel="stylesheet" type="text/css" />

    <link rel="shortcut icon" href="favicon.ico" />
</head>
<body>

    <!-- BEGIN WIDGET TAB -->
    <div class="widget-bg-color-white widget-tab margin-top-20" style="height:539px">
        <ul class="nav nav-tabs caption">
            <li class="caption pull-left" style="margin-top:23px;font-size:1.6rem;">
                <i class="icon-social-twitter font-dark hide"></i>
                <span class="caption-subject font-dark bold uppercase">FAQs</span>
            </li>

            <li class="active pull-right">
                <a href="#generalFAQ" data-toggle="tab"> General </a>
            </li>
            <li class="pull-right">
                <a href="#specificFAQ" data-toggle="tab"> Specific </a>
            </li>
        </ul>
        <div class="tab-content scroller" style="height: 450px;" data-always-visible="1" data-handle-color="#D7DCE2">
            <div class="tab-pane fade active in" id="generalFAQ">

            </div>

            <div class="tab-pane fade" id="specificFAQ">

            </div>
        </div>
    </div>
    <!-- END WIDGET TAB -->    
</body>
</html>

@*<script src="@Url.Content("~/Scripts/jquery.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/js.cookie.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.slimscroll.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.blockui.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/bootstrap-switch.min.js")" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/morris.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/raphael-min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/hammer.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.easing.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.mousewheel.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/mapplic.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.waypoints.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.counterup.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.sparkline.min.js")" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/app.min.js")" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/dashboard.min.js")" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/layout.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/quick-sidebar.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/quick-nav.min.js")" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/select2.full.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/components-select2.min.js")" type="text/javascript"></script>*@
<script src="@Url.Content("~/Scripts/icheck.min.js")" type="text/javascript"></script>
<script type="text/javascript"> 
    //$(document).ready(function () {

    //    $('input').iCheck({
    //    checkboxClass: 'icheckbox_minimal-grey',
    //    radioClass: 'iradio_minimal-grey',
    //    increaseArea: '20%' // optional
    //  });
    //});
</script>
<script type="text/javascript">

            //$(document).ready(function () {
    //    fillFAQsList(operationID);
            //});
    //fillFAQsList(operationID);
            //This is an ajax function to test operation and script display from database.
    function fillFAQsList(opID) {
        //this script is for FAQs
        var FAQURL = '@Url.Action("fillFAQsList", "CallCenter")';

        $.ajax({
            type: 'GET',
            url: FAQURL,
            data: { operationKey:opID },
            dataType: 'json',
            timeout: 10000,
            success: function (data, textStatus, xhr) {

                if (data == 0){}
                    //alert("fillFAQsList Data couldn't be found!");
                else {
                    //alert(opID);
                    $.each(data, function (key, value) {


                        var html = '<div class="widget-news margin-bottom-20" value=' + value.FAQType + '>';
                        html += '<img class="widget-news-left-elem" alt="">';
                        html += '<div class="widget-news-right-body">';
                        html += '<div class="col-lg-7"><h3 class="widget-news-right-body-title"><input class="FAQanswerTemplate" data-OperationID="'+ opID +'"@*" data-FAQQuestionKey="'+here we put the Key needed+'"*@ type="checkbox">' + value.QuestionText + '</h3></div><label class="pull-right"><font><i>' + value.QuestionNote + '&nbsp</i></font></label>';
                        html += '<h5 class="col-lg-12" style="padding-left: 40px; font-size: medium;">' + value.AnswerValue + '</h5>';



                        //    var html = '<div class="widget-news margin-bottom-20" value=' + value.FAQType + '>';
                        //    html += '<img class="widget-news-left-elem" alt="">';
                        //    html += '<div class="widget-news-right-body">';
                        //    html += '<h3 class="widget-news-right-body-title">' + value.QuestionText + '<span class="pull-right">' + value.QuestionNote + '</span></h3>';
                        //    html += '<input type="radio" name="radio1"><label>' + value.AnswerValue + '</label>';
                        //    html += '<input type="radio" name="radio1"><label>' + value.AnswerValue + '</label>';



                        if (value.FAQType == "General") $("#generalFAQ").append(html);
                        else if (value.FAQType == "Specific") $("#specificFAQ").append(html);
                    });

                    $('input').iCheck({
                        checkboxClass: 'icheckbox_minimal-grey',
                        radioClass: 'iradio_minimal-grey'
                    });

                }

            }




        });
    }

        //fillFAQsList(9);

    </script>



    

CallCenterDashboard1/Views/CallCenter/PrintCall.cshtml
@{
    ViewBag.Title = "PrintCall";
    Layout = null;
    int count = 0;
}

<html>
<head>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body >
    <table class="table">
        <tr>
            <th>
                User: @User.Identity.Name
            </th>
            <th>
                <pre>     </pre>
            </th>
            <th>
                Operation Name: @ViewBag.OperationName
            </th>
            <th>
                <pre>     </pre>
            </th>
            <th>
                Call Status: @ViewBag.CallStatus
            </th>
            <th>

            </th>
        </tr>
    </table>

    <table class="table" border="1">
        <tr>
           
            <th>
                Voter Full Name
            </th>
            <th>
                Phone Number Landline/Mobile
            </th>
            <th>
                Balda/Tayfeh/Sejjel
            </th>
            <th>
                Baldat El Sakan
            </th>
            <th>
                Intima2 Siyasi
            </th>
            <th>
                Taswit
            </th>
        </tr>

        @try
        {
            foreach (var item in Model)
            {
                count = count + 1;
                if(count > 100)
                {
                    break;
                }
                <tr>
                    <td>
                        @item["الاسم"] @item["اسم_الأب"] @item["الشهرة"]
                    </td>
                    <td>
                        @item["الهاتف"]/@item["الخليوي"]
                    </td>
                    <td>
                        @item["بلدة_النفوس"]/@item["الطائفة"]/@item["رقم_السجل"]

                    <td>
                        @item["بلدة_السكن"]
                    </td>
                    <td>
                        @item["الانتماء_السياسي"]
                    </td>
                    <td>
                        @item["التصويت"]
                    </td>
                </tr>
                };

            }
        catch
        {

        }


</table>
    <script>
        $(document).ready(function () {
           
            window.print();
        });
    </script>

</body>

</html>