CallCenterDashboard1/Controllers/PMDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CallCenterDashboard1.EDMX;
using CallCenterDashboard1.Models;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using System.Globalization;

namespace CallCenterDashboard1.Controllers
{
    public class PMDashboardController : Controller
    {
        public static string HashCode = "";

        [Authorize]
        // GET: PMDashboard
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult RequestService(string RequestKey, string AllowEdit = "", string individualid = null)
        {
            //individualid = "1001";
            var CallsIncoming = 0;
            var CallsOutGoing = 0;
            var VisitsIncoming = 0;
            var VisitsOutGoing = 0;
            var TotalNumberOfIndividuals = 0;

            RequestKey = RequestKey == null ? "" : RequestKey;
            individualid = individualid == null ? "" : individualid;

            List<GetUsers_Result> usersResult = new List<GetUsers_Result>();
            Dictionary<string, int> groupIndividualsCountDictionary = new Dictionary<string, int>();


            using (BeirutUIEntities PMSPEntities = new BeirutUIEntities())
            {
                usersResult = PMSPEntities.GetUsers(null).ToList<GetUsers_Result>();
                var userGroups = usersResult.Where(x => x.Email == User.Identity.Name).Select(x => x.Group).ToList();

                var userDashBoard = usersResult.First(x => x.UserName == User.Identity.Name).DashBoard;
                ViewBag.DashboardType = userDashBoard.Trim();

                List<GETservice_comm_Result> result2 = new List<GETservice_comm_Result>();
                result2 = PMSPEntities.GETservice_comm(null).ToList<GETservice_comm_Result>();
                ViewData["request"] = "";
                ViewData["Evaluation"] = "";
                //var users = result2.GroupBy(x => x.FromUser).Select(g => g.First());
                ViewData["service_comm"] = result2.Select(group => new SelectListItem { Text = group.comm_name, Value = group.comm_name.Trim() }).ToList();
                ServiceModel model = new ServiceModel();
                model.Request = new GetRequests_Result();
                model.Evaluation = new List<GETServiceEvaluation_Result>();
                model.MokademElTalab = model.MokademElTalab = new GetIndividualsByID_Result();
                model.AllowEdit = AllowEdit;
                string userID = string.Empty;

                List<GetUsers_Result> userList = new List<GetUsers_Result>();

                userList = PMSPEntities.GetUsers(null).ToList<GetUsers_Result>();
                userID = userList.First(x => x.UserName == User.Identity.Name).Id;


                try
                {
                    foreach (string groupName in userGroups)
                    {
                        var userHash = "1 = 1" + usersResult.First(x => x.UserName == User.Identity.Name && x.Group == groupName).AssignedHash;
                        var groupIndividualsCount = Convert.ToInt32(PMSPEntities.CountIndividuals(userHash).ToList()[0]);

                        groupIndividualsCountDictionary.Add(groupName, groupIndividualsCount);
                    }
                }
                catch
                {
                    groupIndividualsCountDictionary.Add("No Group Available", 0);
                }

                List<GetRequestsDatatableFormByRequestType_Result> getRequestsCallsIncoming = new List<GetRequestsDatatableFormByRequestType_Result>();
                getRequestsCallsIncoming = PMSPEntities.GetRequestsDatatableFormByRequestType(null, "Call", null).ToList<GetRequestsDatatableFormByRequestType_Result>();
                getRequestsCallsIncoming = getRequestsCallsIncoming.Where(x => x.RequestedFromUser == userID).ToList();
                getRequestsCallsIncoming = getRequestsCallsIncoming.OrderByDescending(x => x.RequestKey).ToList();
                CallsIncoming = getRequestsCallsIncoming.Count;

                List<GetRequestsDatatableFormByRequestType_Result> getRequestsCallsOutGoing = new List<GetRequestsDatatableFormByRequestType_Result>();
                getRequestsCallsOutGoing = PMSPEntities.GetRequestsDatatableFormByRequestType(null, "Call", null).ToList<GetRequestsDatatableFormByRequestType_Result>();
                getRequestsCallsOutGoing = getRequestsCallsOutGoing.Where(x => x.RequestedCreatedByUser == userID).ToList().Where(x => x.notify == "0").ToList<GetRequestsDatatableFormByRequestType_Result>();
                getRequestsCallsOutGoing = getRequestsCallsOutGoing.OrderByDescending(x => x.RequestKey).ToList();
                CallsOutGoing = getRequestsCallsOutGoing.Count;

                List<GetRequestsDatatableFormByRequestType_Result> getRequestsVisitsIncoming = new List<GetRequestsDatatableFormByRequestType_Result>();
                getRequestsVisitsIncoming = PMSPEntities.GetRequestsDatatableFormByRequestType(null, "Visit", null).ToList<GetRequestsDatatableFormByRequestType_Result>();
                getRequestsVisitsIncoming = getRequestsVisitsIncoming.Where(x => x.RequestedFromUser == userID).ToList();
                getRequestsVisitsIncoming = getRequestsVisitsIncoming.OrderByDescending(x => x.RequestKey).ToList();
                VisitsIncoming = getRequestsVisitsIncoming.Count;

                List<GetRequestsDatatableFormByRequestType_Result> getRequestsVisitsOutGoing = new List<GetRequestsDatatableFormByRequestType_Result>();
                getRequestsVisitsOutGoing = PMSPEntities.GetRequestsDatatableFormByRequestType(null, "Visit", null).ToList<GetRequestsDatatableFormByRequestType_Result>();
                getRequestsVisitsOutGoing = getRequestsVisitsOutGoing.Where(x => x.RequestedCreatedByUser == userID).ToList().Where(x => x.notify == "0").ToList<GetRequestsDatatableFormByRequestType_Result>();
                getRequestsVisitsOutGoing = getRequestsVisitsOutGoing.OrderByDescending(x => x.RequestKey).ToList();
                VisitsOutGoing = getRequestsVisitsOutGoing.Count;

                TotalNumberOfIndividuals = userGroups.Count;

                ViewBag.CallsIncoming = CallsIncoming;
                ViewBag.CallsOutGoing = CallsOutGoing;
                ViewBag.VisitsIncoming = VisitsIncoming;
                ViewBag.VisitsOutGoing = VisitsOutGoing;
                ViewBag.TotalNumberOfIndividuals = TotalNumberOfIndividuals;
                ViewBag.groupIndividualsCountDictionary = groupIndividualsCountDictionary;

                if (RequestKey != null)
                {
                    if (RequestKey != "")
                    {
                        model.Request = PMSPEntities.GetRequests(null, "1").ToList().Where(x => x.RequestKey == int.Parse(RequestKey)).FirstOrDefault();
                        model.Evaluation = PMSPEntities.GETServiceEvaluation(RequestKey).ToList();
                        model.MokademElTalab = PMSPEntities.GetIndividualsByID(model.Request.IndividualKey).FirstOrDefault();
                        model.TalebElKhidma = PMSPEntities.GetIndividualsByID(model.Request.AskForServiceKey).FirstOrDefault();
                        return View(model);
                    }
                }


                if (individualid != "")
                {
                    var individual = new GetIndividualsByID_Result();

                    individual = PMSPEntities.GetIndividualsByID(individualid).FirstOrDefault();

                    //ViewBag.Individual = Json(individual, JsonRequestBehavior.AllowGet);
                    var ttt = new JavaScriptSerializer().Serialize(individual);
                    ViewBag.Individual = new JavaScriptSerializer().Serialize(individual);
                }

            }


            return View();
        }

       

        public JsonResult CreateServiceRequest(int requestID, string requestedFromUser, string requestedCreatedByUser, string requestName, string requestDate, string requestSeen, string requestCompleted, string individualKey, string actionVisitInternalExternal, string actionTitle, string actionComment, string actionDueDate, string actionMaxDueDate, string communication, string introducer, string serviceDescription, string serviceReason, string note, string reminderDay, string reminderTime, string status, string comment, string requestVersion, string askForServiceKey, string askForServiceType, string serviceType, string serviceReference, string serviceLevel, string pointOfService, string priority, string notify, string isHost = null, string inviteeComment = null, string attendingStatus = null, string inviteeName = null, string individualsInvitees = null, string usersInvitees = null, string silatElTawasol = "")
        {
            List<string> usersToNotify = new List<string>();
            int requestKey = 0;
            using (BeirutUIEntities PMSPEntities = new BeirutUIEntities())
            {
                if (requestID == 0)
                {
                    var actions = PMSPEntities.GetActionByUsers(null).ToList<GetActionByUsers_Result>();
                    AccountController acc = new AccountController();
                    List<GetUsers_Result> allServiceUsers = new List<GetUsers_Result>();
                    allServiceUsers = acc.GetServiceUsers().Where(x => x.DashBoard.Trim().ToLower() == "ServiceProvider".Trim().ToLower()).ToList();
                    int count = PMSPEntities.GetMou3arref(introducer).ToList().Where(x => x.Name == introducer).Count();
                    if (count == 0)
                    {
                        PMSPEntities.CreateMou3arref(introducer);
                    }
                    foreach (var user in allServiceUsers)
                    {

CallCenterDashboard1/Views/PMDashboard/Individuals.cshtml
@using CallCenterDashboard1.Models
@{
    ViewBag.Title = "Individuals";
    Layout = null;
}

<h2 style="margin-top:0px">Individuals</h2>


<div>
    <ul class="nav nav-tabs">

        <li id="add_individual_tab" class="active">
            @*<a data-toggle="tab">
                @if (ViewBag.IndividualID == "0")
                {
                    <text>
                        Add NonVoters
                    </text>
                }
                else
                {
                    <text>
                        Add Individuals
                    </text>
                }

            </a>*@
        </li>
        @*<li id="view_individual_tab">
            <a data-toggle="tab">
                @if (ViewBag.IndividualID == "0")
                {
                    <text>
                        View NonVoters
                    </text>
                }
                else
                {
                    <text>
                        View NonVoters
                    </text>
                }

            </a>
        </li>*@
    </ul>
</div>


<div id="addindividual">
    @Html.Action("AddIndividual", "PMDashboard", new { id = ViewBag.IndividualID })
</div>

@*<div id="allIndividual" style="display:none">
    @Html.Action("AllIndividual", "Individuals", new { id = ViewBag.IndividualID })
</div>*@

<script>
    var table;

    //$('#BirthOfDate').datepicker({
    //    changeMonth: true,
    //    changeDay: true,
    //    showButtonPanel: true,
    //    dateFormat: 'mm-dd'
    //});
   

    $(document).ready(function () {

        setTimeout(function () {

            var individualID = '@ViewBag.IndividualID';

            var HashCode = "AND ID = N'" + individualID + "'"
            if (individualID != "")
            {
                var ajaxSource = '@Url.Action("getIndividualsDashBoardByHash", "PMDashboard")' + '/?userHash=' + HashCode;

                $.ajax({
                    type: "GET",
                    cache: false,
                    url: ajaxSource,
                    dataType: "json",
                    success: function (res) {
                        for (var i in res.data) {
                            var key = i;
                            var val = res.data[i];
                            for (var j in val) {
                                var sub_key = j;
                                var sub_val = val[j];

                                var selectedOrNotRadioButton = val[j] == null ? "NA" : val[j];

                                console.log("val[" + j + "] = " + val[j]);
                                //console.log("selectedOrNotRadioButton" + j + " = " + selectedOrNotRadioButton.toLowerCase());
                                
                                //if (val[j] != null) {
                                //    selectedOrNotRadioButton = val[j].length > 0 ? "true" : val[j];
                                //}

                                $('*[data-value="' + sub_key + '"][value="' + selectedOrNotRadioButton + '"]').attr('checked', 'checked');

                                //$('[data-value="تأثير_المال"]').val('True').trigger('change');
                            }
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        console.log("error radio button")
                    }
                });


            }
       
        }, 2000);

        

    });


    $("#view_individual_tab").click(function () {
        $("#allIndividual").css("display", "block");
        $("#addindividual").css("display", "none");

    });

    $("#add_individual_tab").click(function () {
        $("#addindividual").css("display", "block");
        $("#allIndividual").css("display", "none");

    });


    var esem;
    var kada2_noufous;
    var baldat_noufous;
    var kada2_sakan;
    var baldat_sakan;
    var alhay;
    var almehna;
    var aldakhel;
    var alintima2_alsyasi;
    var altaswit;
    var wade3alenti5abi;
    $('#allindividuals tbody').on('click', 'tr', function () {
        var data = table.row(this).data();
        esem = data[1];
        kada2_noufous = data[2];
        baldat_noufous = data[3];
        kada2_sakan = data[4];
        baldat_sakan = data[5];
        alhay = data[6];
        almehna = data[7];
        aldakhel = data[8];
        alintima2_alsyasi = data[9];
        altaswit = data[10];
        wade3alenti5abi = data[11];
    });

    $("#edit_individual").click(function () {
        $("#individualname").val(esem);
        $("#kadaa_al_noufous").val(kada2_noufous);
        $("#baldat_alnoufous").val(baldat_noufous);
        $("#kadaa_alsakan").val(kada2_sakan);
        $("#baldat_alsakan").val(baldat_sakan);
        $("#alhay").val(alhay);
        $("#almehna").val(almehna);
        $("#aldakhel").val(aldakhel);
        $("#alintima2_alsyasi").val(alintima2_alsyasi);
        $("#altaswit").val(altaswit);
        $("#alwade3_alinti5abi").val(wade3alenti5abi);
        $("#addindividual").css("display", "block");
        $("#allIndividual").css("display", "none");

        $("#save_individual").css("display", "block");
        $("#submit_individual").css("display", "none");
    });


</script>

@*Load Indivdual Texts*@
<script>
    var selectedIndividualToEdit;
    var parentSelect;
    $(document).ready(function () {
        //selectedIndividualToEdit = JSON.parse(sessionStorage.getItem('selectedIndividualToEdit'));
        //if (selectedIndividualToEdit != "") {


        //    $("#individualname").val(selectedIndividualToEdit.الاسم);
        //    $("#fathername").val(selectedIndividualToEdit.اسم_الأب);
        //    $("#chohra").val(selectedIndividualToEdit.الشهرة);
        //    $("#kadaa_al_noufous").val(selectedIndividualToEdit.قضاء_النفوس);
        //    $("#baldat_alnoufous").val(selectedIndividualToEdit.بلدة_النفوس);
        //    $("#mothername").val(selectedIndividualToEdit.اسم_الام);
        //    $("#rakemsejel").val(selectedIndividualToEdit.رقم_السجل);
        //    //$("#chohra").val(selectedIndividualToEdit.رقم_السجل);
        //    $("#alhay").val(selectedIndividualToEdit.الحي);
        //    $("#khelyawi").val(selectedIndividualToEdit.الخليوي);
        //    $("#alintima2_alsyasi").val(selectedIndividualToEdit.الانتماء_السياسي);
        //    $("#ehtimamat").val(selectedIndividualToEdit.الاهتمامات);
        //    $("#hatef").val(selectedIndividualToEdit.الهاتف);
        //    $("#aldakhel").val(selectedIndividualToEdit.الدخل);
        //    $("#familyname").val(selectedIndividualToEdit.العائلة);
        //    $("#almehna").val(selectedIndividualToEdit.المهنة);
        //    $("#hewayat").val(selectedIndividualToEdit.الهوايات);
        //    $("#syaratnakel").val(selectedIndividualToEdit.استعمال_سيارته_للنقل);
        //    $("#baldat_alsakan").val(selectedIndividualToEdit.بلدة_السكن);
        //    $("#alwade3_alinti5abi").val(selectedIndividualToEdit.الوضع_الانتخابي);
        //    $("#nakel").val(selectedIndividualToEdit.بحاجة_لنقل);
        //    $("#buildingname").val(selectedIndividualToEdit.بناية);
        //    //$("#buildingname").val(selectedIndividualToEdit.بلد_السفر);
        //    $("#moulahazat").val(selectedIndividualToEdit.ملاحظات);
        //    $("#kadaa_alsakan").val(selectedIndividualToEdit.قضاء_السكن);
        //    $("#mouftah").val(selectedIndividualToEdit.مفتاح);
        //    $("#moultazim").val(selectedIndividualToEdit.ملتزم);
        //    $("#mandoubhali").val(selectedIndividualToEdit.مندوب_حالي);
        //    $("#mandoubsabek").val(selectedIndividualToEdit.مندوب_سابق);
        //    $("#cstreetname").val(selectedIndividualToEdit.شارع);
        //    $("#altaswit").val(selectedIndividualToEdit.التصويت);
        //    $("#khadamatnumber").val(selectedIndividualToEdit.عدد_الخدمات);
        //    $("#birthdaydate").val(selectedIndividualToEdit.تاريخ_الولادة__يوم_شهر_);
        //    $("#jam3ya2").val(selectedIndividualToEdit.جمعية_2);
        //    $("#jam3ya1").val(selectedIndividualToEdit.جمعية_1);
        //    $("#socalmedia").val(selectedIndividualToEdit.has_Instagram_Account);
        //    $("#mou2aser").val(selectedIndividualToEdit.مؤثر__influencer___);
        //    $("#khelyawi").val(selectedIndividualToEdit.الخليوي);



        //    //selectedIndividualToEdit.Area_of_influence
        //    //selectedIndividualToEdit.CheckBox
        //    //selectedIndividualToEdit.Has_Facebook_Account
        //    //selectedIndividualToEdit.Has_Twitter_Account
        //    //selectedIndividualToEdit.Hash
        //    //selectedIndividualToEdit.ID
        //    //selectedIndividualToEdit.Voted2009
        //    //selectedIndividualToEdit.addr_abroad
        //    //selectedIndividualToEdit.country
        //    //selectedIndividualToEdit.has_phone_number_abroad
        //    //selectedIndividualToEdit.mobile_abroad
        //    //selectedIndividualToEdit.mohafaza
        //    //selectedIndividualToEdit.phone_abroad
        //    //selectedIndividualToEdit.الانتماء_السياسي_group_
        //    //selectedIndividualToEdit.الاولاد_دون_21__details_
        //    //selectedIndividualToEdit.الجنس
        //    //selectedIndividualToEdit.انتخب_2009
        //    //selectedIndividualToEdit.انتخب_2010
        //    //selectedIndividualToEdit.انتخب_2016
        //    //selectedIndividualToEdit.بريد_الكتروني
        //    //selectedIndividualToEdit.تأثير_المال
        //    //selectedIndividualToEdit.جنس_الاولاد
        //    //selectedIndividualToEdit.سنة_الولادة
        //}
        //sessionStorage.setItem('selectedIndividualToEdit', "");

    });

</script>

CallCenterDashboard1/Views/PMDashboard/_AddNonVoter.cshtml
@{
    ViewBag.Title = "_AddNonVoter";
    Layout = null;
}

<style>
    .font-green {
        color: #000000 !important;
    }
    .row{
             margin-left: 0px !important; 
            margin-right: 0px !important; 
    }
</style>




<body>
    <div class="row" id="addindividual">

        @*<h3 class="font-green">Company Information</h3>*@


        <div class="col-lg-3" style="float:right;margin-top:10px;width:26%">
            <label style="float:right"> :قضاء النفوس </label>

            <select id="kadaa_txt" data-value="قضاء_النفوس" class="form-control" style="width:65% !important;float:right" type="text"></select>

        </div>

        <div class="col-lg-3" style="float:right;margin-top:10px;">
            <label style="float:right"> :بلدة النفوس </label>
            <select id="baldat_noufous_txt" data-value="بلدة_النفوس" class="form-control" style="width:65% !important;" type="text"></select>

        </div>

        <div class="col-lg-3" style="float:right;margin-top:10px;">
            <label style="float:right"> :رقم السجل </label>
            <input id="sejel_text" value="" class="form-control" data-value="رقم_السجل" style="width:65%" type="text" placeholder="" name="" />
        </div>

        <div class="col-lg-3" style="float:right;margin-top:10px;clear:both">
            <label style="float:right"> :الاسم </label>
            <input id="first_name_txt" data-value="الاسم" value="" class="form-control" style="width:65%" type="text" placeholder="" name="" />
        </div>

        <div class="col-lg-3" style="float:right;margin-top:10px;">
            <label style="float:right"> :اسم الأب </label>
            <input id="father_name_txt" value="" data-value="اسم_الأب" class="form-control" style="width:65%" type="text" placeholder="" name="" />
        </div>

        <div class="col-lg-3" style="float:right;margin-top:10px;">
            <label style="float:right"> :الشهرة </label>
            <input id="family_name_txt" data-value="الشهرة" value="" class="form-control" style="width:65%" type="text" placeholder="" name="" />
        </div>

        <div class="col-lg-3" style="float:right;margin-top:10px;clear:both">
            <label style="float:right"> :اسم الأم </label>
            <input id="mother_name_txt" data-value="اسم_الام" value="" class="form-control" style="width:65%" type="text" placeholder="" name="" />
        </div>


        @*<div class="col-lg-3" style="float:right;margin-top:10px">
                <label style="float:right"> :العائلة </label>
                <input id="" value="" class="form-control" style="width:65%" type="text" placeholder="" name="" />
            </div>*@

        <div class="col-lg-3" style="float:right;margin-top:10px;">
            <label style="float:right"> :قضاء السكن </label>

            <select id="lives_in_kadaa_txt" data-value="قضاء_السكن" class="form-control" style="width:65% !important;" type="text"></select>

        </div>

        <div class="col-lg-3" style="float:right;margin-top:10px;">
            <label style="float:right"> :بلدة السكن </label>
            <select id="lives_in_balda_txt" data-value="بلدة_السكن" class="form-control" style="width:65% !important;" type="text"></select>
        </div>

        <div class="col-lg-3" style="float:right;margin-top:10px;clear:both">
            <label style="float:right"> :الهاتف </label>
            <input id="Phonetext" data-value="الهاتف" value="" class="form-control phone_text" style="width:65%" type="text" placeholder="" name="" />
        </div>

        <div class="col-lg-3" style="float:right;margin-top:10px;">
            <label style="float:right"> :المهنة </label>
            <input id="almehna" value="" data-value="المهنة" class="form-control" style="width:65%" type="text" placeholder="" name="" />
        </div>



    </div>
    <div class="row">
        @*<button type="submit" id="submit_individual" class="btn btn-success uppercase " style="margin-top: 23px;">Submit</button>*@
        <button type="submit" id="save_individual" style="margin-top: 23px;" class="btn btn-success uppercase ">Save</button>
    </div>




    <script src="@Url.Content("~/Scripts/Metronic/Datatables/datatable.js")" type="text/javascript"> </script>
</body>